name: Update Packages
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *' # Every day at 08:00 UTC

jobs:
  update-packages:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.
      contents: write # Require write permission to push changes to the repository.

    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Install requirements
      run: |
        make install_requirements

    - name: Run package list update
      run: |
        make run
      env:
        ACA_DS_POOL_ENDPOINT: ${{ secrets.ACA_DS_POOL_ENDPOINT }}

    - name: Update packages.txt
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
          exit 0
        fi
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add packages.txt
        git commit -m "Update packages.txt"
        git push
